name: Fetch YARA Rules from defender2yara

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours

jobs:
  fetch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch YARA rules from defender2yara repository
        run: |
          rm -rf Lists/Others/Defender_yara_rules/
          git clone --depth 1 --branch yara-rules https://github.com/t-tani/defender2yara.git temp_defender2yara
          mkdir -p Lists/Others/Defender_yara_rules/
          cp -r temp_defender2yara/* Lists/Others/Defender_yara_rules/
          rm -rf temp_defender2yara

      - name: Commit and Push YARA rules
        run: |
          git pull
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add Lists/Others/Defender_yara_rules/*
          git commit -m "Updated YARA rules from defender2yara" --allow-empty
          git push
