name: Create Bookmarks on README Change

on:
  push:
    paths:
      - "README.md"
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found, skipping installation"

      - name: Run script
        run: |
          cd _utils/
          python create_bookmarks_file_to_import.py

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Stash changes before pulling to avoid conflicts
          git stash --include-untracked
          git pull --rebase
          git stash pop || echo "No stashed changes to apply"

          git add "_utils"
          git commit -m "Update Defender signatures list" --allow-empty
          git push
