name: Fetch MaxMind Databases Daily

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  update-geoip:
    runs-on: ubuntu-latest
    environment: maxmind  # Ensures secrets are loaded from the "maxmind" environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests  

      - name: Debug Secrets (Check If They Exist)
        run: |
          [[ -z "${{ secrets.MAXMIND_LICENSE_KEY }}" ]] && echo "❌ MAXMIND_LICENSE_KEY is missing!" || echo "✅ MAXMIND_LICENSE_KEY is set"
          [[ -z "${{ secrets.MAXMIND_ACCOUNT_ID }}" ]] && echo "❌ MAXMIND_ACCOUNT_ID is missing!" || echo "✅ MAXMIND_ACCOUNT_ID is set"

      - name: Run Fetch Script
        working-directory: Lists/ASNs/correlation_maxmind_geo_db/
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
          MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT_ID }}
        run: |
          echo "🚀 Running fetch_maxmind_databases_daily.py..."
          python fetch_maxmind_databases_daily.py || echo "❌ Script failed! Check logs."
