name: Hourly hideip.me Update

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  fetch-hideip-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download .txt Files from hideip.me
        run: |
          # Define the target directory
          TARGET_DIR=Lists/PROXY/hideip.me
          mkdir -p $TARGET_DIR

          # List of .txt files to download
          FILES=(
            "connect.txt"
            "http.txt"
            "https.txt"
            "socks4.txt"
            "socks5.txt"
          )

          # Base URL of the raw files in the source repository
          BASE_URL="https://raw.githubusercontent.com/zloi-user/hideip.me/main"

          # Download each file
          for FILE in "${FILES[@]}"; do
            curl -o "$TARGET_DIR/$FILE" "$BASE_URL/$FILE"
          done

      - name: List files in the root directory
        run: ls -la

      - name: List files in the target directory
        run: ls -la Lists/PROXY/hideip.me

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/PROXY/hideip.me/*
          git commit -m "Update hourly hideip.me files" --allow-empty
          git push
