name: Purge Old Git LFS Files

on:
  workflow_dispatch:  # Allow manual execution

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (Full history)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0  # Needed to get full LFS history

      - name: Ensure Git LFS is Initialized
        run: |
          echo "🚀 Initializing Git LFS..."
          git lfs install || echo "✅ Git LFS already initialized."

      - name: List All LFS-Tracked Files
        run: |
          echo "🚀 Listing all LFS-tracked files..."
          git lfs ls-files -l || echo "✅ No LFS files detected."

      - name: Detect Large LFS Files and Remove Old Versions
        run: |
          echo "🚀 Detecting large LFS files..."
          LFS_FILES=$(git lfs ls-files -l | awk '{print $2}')
          
          if [ -z "$LFS_FILES" ]; then
            echo "✅ No LFS files detected. Exiting..."
            exit 0
          fi

          echo "🚀 Removing old LFS-tracked files..."
          for FILE in $LFS_FILES; do
            if [ -f "$FILE" ]; then
              echo "❌ Removing $FILE from LFS tracking..."
              git lfs uninstall || echo "✅ Git LFS already uninstalled."
              git rm --cached "$FILE"
            else
              echo "⚠️ Warning: File $FILE does not exist, skipping..."
            fi
          done

          git commit -m "Remove old LFS files to free up storage" || echo "✅ No changes to commit"
          git push origin main --force

      - name: Cleanup LFS Objects
        run: |
          echo "🚀 Cleaning up LFS storage..."
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
          git lfs prune --force
          git lfs push --all origin main
