name: Sinkholed Domains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  download_and_scan:
    runs-on: ubuntu-latest
    environment: ICANN  

    steps:
      - name: Checkout awesome-lists Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Debug GitHub Secrets
        run: |
          echo "ICANN_USERNAME is set: ${{ secrets.ICANN_USERNAME != '' }}"
          echo "ICANN_PASSWORD is set: ${{ secrets.ICANN_PASSWORD != '' }}"
          
      #- name: debug test authent API curl 
      #  run: |
      #    curl -X POST "https://account-api.icann.org/api/authenticate" \
      #      -H "Content-Type: application/json" \
      #      -H "Accept: application/json" \
      #      -H "User-Agent: Mozilla/5.0 (compatible; CZDS-Client/1.0; +https://your-repo-url)" \
      #      -d '{"username": "${{ secrets.ICANN_USERNAME }}", "password": "${{ secrets.ICANN_PASSWORD }}"}' \
      #      -v

      - name: Clone CZDS API Client Repo
        working-directory: Lists/Domains/sinkholed_servers
        run: git clone https://github.com/mthcht/czds-api-client-python

      - name: Create config.json with Secrets
        working-directory: Lists/Domains/sinkholed_servers/czds-api-client-python
        run: |
          echo '{
            "icann.account.username": "'"${ICANN_USERNAME}"'",
            "icann.account.password": "'"${ICANN_PASSWORD}"'",
            "authentication.base.url": "https://account-api.icann.org",
            "czds.base.url": "https://czds-api.icann.org",
            "working.directory": "zones/"
          }' | jq . > config.json
        env:
          ICANN_USERNAME: ${{ secrets.ICANN_USERNAME }}
          ICANN_PASSWORD: ${{ secrets.ICANN_PASSWORD }}

      - name: Run Download Script
        working-directory: Lists/Domains/sinkholed_servers/czds-api-client-python
        run: python3 download.py
        
      - name: Install Required Python Modules
        run: pip install pandas
        
      - name: Search for Sinkholed Servers
        working-directory: Lists/Domains/sinkholed_servers
        run: python3 search_for_sinkholed_servers.py czds-api-client-python/zones/zonefiles/ sinkhole_ns_list.csv

      - name: Cleanup CZDS API Client
        working-directory: Lists/Domains/sinkholed_servers
        run: rm -rf czds-api-client-python
        
      - name: transform csv to json
        working-directory: Lists/Domains/sinkholed_servers
        run: python3 transform_csv_to_json.py --csv-file sinkholed_domains.csv
        
      - name: Commit and Push Updated Sinkhole List
        working-directory: Lists/Domains/sinkholed_servers
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add sinkholed_domains.csv sinkholed_domains.json
          git commit -m "Update sinkholed domains list [Automated]"
          git push origin main
