name: Sinkholed Domains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download_and_scan:
    runs-on: ubuntu-latest
    environment: ICANN  

    steps:
      - name: Checkout awesome-lists Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Debug GitHub Secrets
        run: |
          echo "ICANN_USERNAME is set: ${{ secrets.ICANN_USERNAME != '' }}"
          echo "ICANN_PASSWORD is set: ${{ secrets.ICANN_PASSWORD != '' }}"

      - name: Clone CZDS API Client Repo
        working-directory: Lists/Domains/sinkholed_servers
        run: git clone https://github.com/mthcht/czds-api-client-python

      - name: Create config.json with Secrets
        working-directory: Lists/Domains/sinkholed_servers/czds-api-client-python
        run: |
          echo '{
            "icann.account.username": "'"${{ secrets.ICANN_USERNAME }}"'",
            "icann.account.password": "'"${{ secrets.ICANN_PASSWORD }}"'",
            "authentication.base.url": "https://account-api.icann.org",
            "czds.base.url": "https://czds-api.icann.org",
            "working.directory": "/zones/"
          }' > config.json

          cat config.json  # Debugging step to verify the file content

      - name: Run Download Script
        working-directory: Lists/Domains/sinkholed_servers/czds-api-client-python
        run: python3 download.py

      - name: Extract Zone Files
        working-directory: Lists/Domains/sinkholed_servers
        run: python3 extract_zonefiles.py

      - name: Search for Sinkholed Servers
        working-directory: Lists/Domains/sinkholed_servers
        run: python3 search_for_sinkholed_servers.py /zones/extracted_zonefiles/ sinkhole_ns_list.csv

      - name: Cleanup CZDS API Client
        working-directory: Lists/Domains/sinkholed_servers
        run: rm -rf czds-api-client-python

      - name: Commit and Push Updated Sinkhole List
        working-directory: Lists/Domains/sinkholed_servers
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add sinkhole_ns_list.csv
          git commit -m "Update sinkholed domains list [Automated]"
          git push origin main
