name: Surfshark VPN Update

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:

jobs:
  fetch-surfshark-configs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Surfshark Config Script
        run: |
          cd Lists/VPN/SurfSharkVPN
          python fetch_surfshark_servers_ip_address.py

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/VPN/SurfSharkVPN/surfshark_vpn_servers_domains_and_ips_list.csv
          git commit -m "Update Surfshark domains and IPs" --allow-empty
          git push
