name: Update TOP1M domains

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  fetch-top1M-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the script to update TOP1M
        run: |
          cd Lists/Domains/TOP1M
          python3 download_and_merge_TOP1M.py

      - name: List files in the target directory
        run: ls -la Lists/Domains/TOP1M

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Stash any local changes to avoid conflicts
          git add Lists/Domains/TOP1M/*
          git stash

          # Ensure we pull latest changes before pushing
          git pull --rebase || (echo "Pull failed, applying stash..." && git stash pop)

          # Add updated files
          git add Lists/Domains/TOP1M/*
          git commit -m "Update TOP1M domains files" --allow-empty

          # Push changes
          git push
