name: Update TOP1M domains

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  fetch-top1M-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the script to update TOP1M
        run: |
          cd Lists/Domains/TOP1M
          python3 download_and_merge_TOP1M.py

      - name: List files in the target directory
        run: ls -la Lists/Domains/TOP1M

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Ensure Git detects all changes, including new files
          git add --all Lists/Domains/TOP1M/

          # Check if there are actual changes before committing
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update TOP1M domains files"
            git pull --rebase
            git push
          fi
