name: Daily update RMM lists

on:
  schedule:
    - cron: '10 * * * *'  # Runs every day
  workflow_dispatch:

jobs:
  fetch-RMM-list:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run scripts from the RMM folder
        run: |
          cd Lists/RMM
          python update_RMM_detection.py
    
      - name: List files
        run: ls -la

      - name: List files in the Lists/RMM directory
        run: ls -la Lists/RMM
        
      - name: Commit any changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Lists/RMM/*
          git commit -m "Save changes before rebase" --allow-empty

      - name: Rebase on latest changes
        run: |
          git pull
          git fetch origin
          git rebase origin/main

      - name: Push updated results
        run: |
          git push
