name: Update TOP1M domains

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  fetch-top1M-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the script to update TOP1M
        run: |
          cd Lists/Domains/TOP1M
          python3 download_and_merge_TOP1M.py

      - name: List generated files
        run: ls -lah Lists/Domains/TOP1M/

      - name: Ensure "big files" Release Exists
        id: ensure_release
        run: |
          if ! gh release view "big-files" --json id --jq '.id' > /dev/null 2>&1; then
            echo "No existing release found, creating one..."
            gh release create "big-files" --title "big files" --notes "Release for large files" --repo ${{ github.repository }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Files to "big files" Release
        run: |
          gh release upload "big-files" Lists/Domains/TOP1M/TOP1M_domains.csv --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Link
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/big-files"
          echo $RELEASE_URL > Lists/Domains/TOP1M/TOP1M_domains.link
          cat Lists/Domains/TOP1M/TOP1M_domains.link

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/PROXY/fresh-proxy-list/TOP1M_domains.link
          git commit -m "Update TOP1M link" --allow-empty
          git push
