name: Update TOP1M domains

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  fetch-top1M-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the script to update TOP1M
        run: |
          cd Lists/Domains/TOP1M
          python3 download_and_merge_TOP1M.py

      - name: List files in the target directory
        run: ls -la Lists/Domains/TOP1M

      - name: Get Latest Release ID
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release ID
        id: extract_release_id
        run: |
          RELEASE_ID=$(echo '${{ steps.get_release.outputs.data }}' | jq -r '.[] | select(.name=="big files") | .id' | head -n 1)
          if [ -z "$RELEASE_ID" ]; then
            echo "No existing release found, creating a new one..."
            echo "release_exists=false" >> $GITHUB_ENV
          else
            echo "Existing release found: $RELEASE_ID"
            echo "release_id=$RELEASE_ID" >> $GITHUB_ENV
            echo "release_exists=true" >> $GITHUB_ENV
          fi

      - name: Create Release if Not Exists
        if: env.release_exists == 'false'
        id: create_release
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/releases
          name: "big files"
          tag_name: "big-files"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Created Release ID
        if: env.release_exists == 'false'
        run: |
          RELEASE_ID=$(echo '${{ steps.create_release.outputs.data }}' | jq -r '.id')
          echo "release_id=$RELEASE_ID" >> $GITHUB_ENV

      - name: Upload File to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.release_id }}/assets?name=TOP1M_domains.csv
          asset_path: Lists/Domains/TOP1M/TOP1M_domains.csv
          asset_content_type: text/csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Link
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/big-files"
          echo $RELEASE_URL > Lists/Domains/TOP1M/TOP1M_domains.link
          cat Lists/Domains/TOP1M/TOP1M_domains.link
