name: VPN Combine ALL IP address

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the script to generate the VPN IP list
        working-directory: Lists/VPN
        run: python create_all_vpn_ip_list.py

      - name: List generated files
        run: ls -lah Lists/VPN/

      - name: Ensure Git LFS Tracks the VPN List (Only If Needed)
        run: |
          git lfs install
          if ! grep -q "Lists/VPN/VPN_ALL_IP_List.csv" .gitattributes; then
            echo "🚀 Adding VPN_ALL_IP_List.csv to Git LFS tracking..."
            git lfs track "Lists/VPN/VPN_ALL_IP_List.csv"
            git add .gitattributes
            git commit -m "Enable Git LFS for VPN list" || echo "✅ No LFS changes to commit"
          else
            echo "✅ VPN_ALL_IP_List.csv is already tracked in LFS."
          fi

      - name: Commit and Push Changes Without Keeping History
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Pull latest changes to avoid conflicts
          git pull --rebase || echo "No updates to pull"

          # Force add the updated file
          git add Lists/VPN/VPN_ALL_IP_List.csv

          # Commit with forced overwrite (no history kept)
          git commit -m "Update VPN_ALL_IP_List" || echo "✅ No changes to commit"

          # Push with --force to avoid history accumulation
          git push origin main --force

      - name: Remove Old LFS Objects from Remote Storage
        run: |
          echo "🚀 Pruning old LFS objects..."
          git lfs prune --force
          git lfs push --all origin main
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
