name: VPN Combine ALL IP address

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run the script to generate the VPN IP list
        working-directory: Lists/VPN
        run: python create_all_vpn_ip_list.py

      - name: List generated files
        run: ls -lah Lists/VPN/

      - name: Ensure "big files" Release Exists
        id: ensure_release
        run: |
          if ! gh release view "big-files" --json id --jq '.id' > /dev/null 2>&1; then
            echo "No existing release found, creating one..."
            gh release create "big-files" --title "big files" --notes "Release for large files" --repo ${{ github.repository }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Large File to "big files" Release & Create Link File
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/big-files"

          FILE="Lists/VPN/VPN_ALL_IP_List.csv"
          if [ -f "$FILE" ]; then
            echo "Uploading $FILE..."
            gh release upload "big-files" "$FILE" --clobber
            echo $RELEASE_URL > "$FILE.link"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove Large File Locally (Avoid Pushing It)
        run: rm -f Lists/VPN/VPN_ALL_IP_List.csv

      - name: Commit and Push Small Files & Release Link
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/VPN/
          git commit -m "Update VPN IP List & release link" --allow-empty
          git push
