name: NordVPN Data Processing

on:
  schedule:
    - cron: '0 */20 * * *'  # Runs at minute 0 every 20 hours
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requests
        run: |
          python -m pip install --upgrade pip
          pip install requests logging beautifulsoup4

      - name: Run the script
        run: python Lists/VPN/NordVPN/get_nordvpn_ips_list.py

      - name: List files in the root directory
        run: ls -la

      - name: List files in the Lists/VPN/NordVPN/ directory
        run: ls -la Lists/VPN/NordVPN/
      - name: Move output files to correct directory (if necessary)
        run: |
          mv nordvpn_ips_list.csv Lists/VPN/NordVPN/ || echo "File not found in root."

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/VPN/NordVPN/nordvpn_ips_list.csv
          git commit -m "Update NordVPN IPs list" --allow-empty
          git push

      - name: Upload csv Results
        uses: actions/upload-artifact@v3
        with:
          name: NordVPN-IP-data-csv
          path: Lists/VPN/NordVPN/nordvpn_ips_list.csv
